extends:
  - 'typescript-shareable'

parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2019
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true

settings:
  react:
    version: detect

overrides:
  ###
  # Test file overrides
  ###
  - files: ['**/*.test.tsx', '**/jest/**']
    env:
      jest: true
